global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: json_exporter
    static_configs:
      - targets: ['json_exporter:7979']

  - job_name: json_agents
    metrics_path: /probe
    params:
      module: [agent]
    static_configs:
      - targets:
          - http://agent_a:9101/audit.json
          - http://agent_b:9102/audit.json
        labels:
          group: lab
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979
