global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 1) Scrute les agents via json_exporter /probe (multi-target pattern)
  - job_name: 'json_agents'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [agent]
    static_configs:
      - targets:
          - http://agent_a:9101/audit.json
          - http://agent_b:9102/audit.json
        labels:
          group: lab
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: json_exporter:7979
      - source_labels: [__param_target]
        target_label: instance

  # 2) Scrute l’exporter lui-même
  - job_name: 'json_exporter'
    static_configs:
      - targets: ['json_exporter:7979']
